const words = [
  { word: "Hund", gender: "der" },
  { word: "Katze", gender: "die" },
  { word: "Haus", gender: "das" },
  { word: "Auto", gender: "das" },
  { word: "Baum", gender: "der" },
  { word: "Blume", gender: "die" },
  { word: "Buch", gender: "das" },
  { word: "Stuhl", gender: "der" },
  { word: "Tasche", gender: "die" },
  { word: "Fenster", gender: "das" },
  { word: "Apfel", gender: "der" },
  { word: "Banane", gender: "die" },
  { word: "Wasser", gender: "das" },
  { word: "Tisch", gender: "der" },
  { word: "Lampe", gender: "die" },
  { word: "Kind", gender: "das" },
  { word: "Vogel", gender: "der" },
  { word: "Sonne", gender: "die" },
  { word: "Brot", gender: "das" },
  { word: "Schrank", gender: "der" },

  { word: "A3-Papier", gender: "das" },
  { word: "A4-Papier", gender: "das" },
  { word: "Abflug", gender: "der" },
  { word: "Abitur", gender: "das" },
  { word: "Abrechnung", gender: "die" },
  { word: "Abschluss", gender: "der" },
  { word: "Abschlussprüfung", gender: "die" },
  { word: "Abstand", gender: "der" },
  { word: "Adressbuch", gender: "das" },
  { word: "Ahnung", gender: "die" },
  { word: "Alarm", gender: "der" },
  { word: "Alter", gender: "das" },
  { word: "Altstadt", gender: "die" },
  { word: "Anfang", gender: "der" },
  { word: "Anfrage", gender: "die" },
  { word: "Angst", gender: "die" },
  { word: "Anhang", gender: "der" },
  { word: "Anruf", gender: "der" },
  { word: "Anschrift", gender: "die" },
  { word: "Antwort", gender: "die" },
  { word: "App", gender: "die" },
  { word: "Arbeitgeberfrage", gender: "die" },
  { word: "Arbeitskollege", gender: "der" },
  { word: "Arbeitskollegin", gender: "die" },
  { word: "Arbeitslosenversicherung", gender: "die" },
  { word: "Arbeitsmarkt", gender: "der" },
  { word: "Arbeitspause", gender: "die" },
  { word: "Arbeitsplan", gender: "der" },
  { word: "Arbeitsplatz", gender: "der" },
  { word: "Arbeitssuche", gender: "die" },
  { word: "Arbeitsverhalten", gender: "das" },
  { word: "Arbeitsvertrag", gender: "der" },
  { word: "Arbeitszimmer", gender: "das" },
  { word: "Arztpraxis", gender: "die" },
  { word: "Arzttermin", gender: "der" },
  { word: "Aufenthalt", gender: "der" },
  { word: "Auftrag", gender: "der" },
  { word: "Ausbildung", gender: "die" },
  { word: "Ausbildungsangebot", gender: "das" },
  { word: "Ausbildungsjahr", gender: "das" },
  { word: "Ausbildungsplatz", gender: "der" },
  { word: "Ausflugsziel", gender: "das" },
  { word: "Ausgabe", gender: "die" },
  { word: "Aushilfe", gender: "die" },
  { word: "Auskunft", gender: "die" },
  { word: "Baby", gender: "das" },
  { word: "Babypause", gender: "die" },
  { word: "Babysitter", gender: "der" },
  { word: "Bahnsteig", gender: "der" },
  { word: "Batterie", gender: "die" },
  { word: "Baumarkt", gender: "der" },
  { word: "Bedingung", gender: "die" },
  { word: "Begegnung", gender: "die" },
  { word: "Behinderung", gender: "die" },
  { word: "Beipackzettel", gender: "der" },
  { word: "Bekanntenkreis", gender: "der" },
  { word: "Beratung", gender: "die" },
  { word: "Bereich", gender: "der" },
  { word: "Bericht", gender: "der" },
  { word: "Bewegung", gender: "die" },
  { word: "Bewerbung", gender: "die" },
  { word: "Bewerbungsfoto", gender: "das" },
  { word: "Bewerbungsgespräch", gender: "das" },
  { word: "Bewerbungsschreiben", gender: "das" },
  { word: "Bezahlung", gender: "die" },
  { word: "Bildung", gender: "die" },
  { word: "Biologie", gender: "die" },
  { word: "Blumenstrauß", gender: "der" },
  { word: "Blut", gender: "das" },
  { word: "Blutdruck", gender: "der" },
  { word: "Blutwert", gender: "der" },
  { word: "Boden", gender: "der" },
  { word: "Brandsäule", gender: "die" },
  { word: "Braut", gender: "die" },
  { word: "Bräutigam", gender: "der" },
  { word: "Brautkleid", gender: "das" },
  { word: "Breite", gender: "die" },
  { word: "Broschüre", gender: "die" },
  { word: "Buchhaltung", gender: "die" },
  { word: "Buchung", gender: "die" },
  { word: "Datei", gender: "die" },
  { word: "Dauer", gender: "die" },
  { word: "Dauerausftrag", gender: "der" },
  { word: "Decke", gender: "die" },
  { word: "Deutschkenntnisse", gender: "die" },
  { word: "Diplom", gender: "das" },
  { word: "Disco", gender: "die" },
  { word: "Dokumentarfilm", gender: "der" },
  { word: "Doppelstunde", gender: "die" },
  { word: "Ding", gender: "das" },
  { word: "Drucker", gender: "der" },
  { word: "Durchfall", gender: "der" },
  { word: "Einnahme", gender: "die" },
  { word: "Einstieg", gender: "der" },
  { word: "E-Mail", gender: "die" },
  { word: "Ende", gender: "das" },
  { word: "Energie", gender: "die" },
  { word: "Energieeffizienz", gender: "die" },
  { word: "Elternabend", gender: "der" },
  { word: "Esszimmer", gender: "das" },
  { word: "Existenz", gender: "die" },
  { word: "Existenzgründerkurs", gender: "der" },
  { word: "Fach", gender: "das" },
  { word: "Fachabitur", gender: "das" },
  { word: "Fachhochschule", gender: "die" },
  { word: "Fachrichtung", gender: "die" },
  { word: "Fähigkeit", gender: "die" },
  { word: "Fahrradstadt", gender: "die" },
  { word: "Fahrradweg", gender: "der" },
  { word: "Familienmitglied", gender: "das" },
  { word: "Familientag", gender: "der" },
  { word: "Familienwagen", gender: "der" },
  { word: "Fantasie", gender: "die" },
  { word: "Farbroller", gender: "der" },
  { word: "Fehler", gender: "der" },
  { word: "Feiertag", gender: "der" },
  { word: "Fernsehen", gender: "das" },
  { word: "Fliese", gender: "die" },
  { word: "Flug", gender: "der" },
  { word: "Flugticket", gender: "das" },
  { word: "Förderschule", gender: "die" },
  { word: "Förderung", gender: "die" },
  { word: "Fortbildung", gender: "die" },
  { word: "Fotografie", gender: "die" },
  { word: "Freitagvormittag", gender: "der" },
  { word: "Fremdsprache", gender: "die" },
  { word: "Freundschaft", gender: "die" },
  { word: "Fußballverein", gender: "der" },
  { word: "Gerät", gender: "das" },
  { word: "Gerechtigkeit", gender: "die" },
  { word: "Gericht", gender: "das" },
  { word: "Gesamtschule", gender: "die" },
  { word: "Geschenk", gender: "das" },
  { word: "Geschichte", gender: "die" },
  { word: "Geschirr", gender: "das" },
  { word: "Gesprächsthema", gender: "das" },
  { word: "Gewitter", gender: "das" },
  { word: "Girokonto", gender: "das" },
  { word: "Gitarre", gender: "die" },
  { word: "Glückwunsch", gender: "der" },
  { word: "Glückwunschkarte", gender: "die" },
  { word: "Grammatikerklärung", gender: "die" },
  { word: "Hauptschule", gender: "die" },
  { word: "Hauptspeise", gender: "die" },
  { word: "Hausaufgabenhilfe", gender: "die" },
  { word: "Haushalt", gender: "der" },
  { word: "Hausmüll", gender: "der" },
  { word: "Hausratversicherung", gender: "die" },
  { word: "Haustier", gender: "das" },
  { word: "Heim", gender: "das" },
  { word: "Heimatverein", gender: "der" },
  { word: "Heimwerker", gender: "der" },
  { word: "Hilfe", gender: "die" },
  { word: "Himmel", gender: "der" },
  { word: "Hochzeitsfeier", gender: "die" },
  { word: "Hochzeitstag", gender: "der" },
  { word: "Hütte", gender: "die" },
  { word: "Internetseite", gender: "die" },
  { word: "Internet", gender: "das" },
  { word: "Jugend", gender: "die" },
  { word: "Kaffeeautomat", gender: "der" },
  { word: "Kaffeekanne", gender: "die" },
  { word: "Kamera", gender: "die" },
  { word: "Kapazität", gender: "die" },
  { word: "Karnevalsverein", gender: "der" },
  { word: "Karteikarte", gender: "die" },
  { word: "Kartoffelsuppe", gender: "die" },
  { word: "Katalog", gender: "der" },
  { word: "Katze", gender: "die" },
  { word: "Kaution", gender: "die" },
  { word: "Kerze", gender: "die" },

  { word: "Kochidee", gender: "die" },
  { word: "Kochkurs", gender: "der" },
  { word: "Koffer", gender: "der" },
  { word: "Komma", gender: "das" },
  { word: "Konto", gender: "das" },
  { word: "Kontogebühr", gender: "die" },
  { word: "Kopie", gender: "die" },
  { word: "Körper", gender: "der" },
  { word: "Krankenversicherung", gender: "die" },
  { word: "Krankenwagen", gender: "der" },
  { word: "Krankheit", gender: "die" },
  { word: "Kreativität", gender: "die" },
  { word: "Kredit", gender: "der" },
  { word: "Kreditkarte", gender: "die" },
  { word: "Küchenhilfe", gender: "die" },
  { word: "Küchenstudio", gender: "das" },
  { word: "Kunst", gender: "die" },
  { word: "Kurs", gender: "der" },
  { word: "Kursangebot", gender: "das" },
  { word: "Küste", gender: "die" },
  { word: "Lernkarte", gender: "die" },
  { word: "Liebe", gender: "die" },
  { word: "Lied", gender: "das" },
  { word: "Löffel", gender: "der" },
  { word: "Lokal", gender: "das" },
  { word: "Luft", gender: "die" },
  { word: "Magen", gender: "der" },
  { word: "Männerfreundschaft", gender: "die" },
  { word: "Maschine", gender: "die" },
  { word: "Maß", gender: "das" },
  { word: "Massage", gender: "die" },
  { word: "Mathematik", gender: "die" },

  { word: "Möglichkeit", gender: "die" },
  { word: "Monatskarte", gender: "die" },
  { word: "Monatsmiete", gender: "die" },
  { word: "Museum", gender: "das" },
  { word: "Muskel", gender: "der" },
  { word: "Mut", gender: "der" },
  { word: "Nachhilfe", gender: "die" },
  { word: "Nachricht", gender: "die" },
  { word: "Nachspeise", gender: "die" },
  { word: "Nebenwirkung", gender: "die" },
  { word: "Netzwerk", gender: "das" },
  { word: "Nahrungsmittel", gender: "das" },
  { word: "Nagetier", gender: "das" },
  { word: "Nachbar", gender: "der" },
  { word: "Nachbarschaft", gender: "die" },
  { word: "Ohr", gender: "das" },
  { word: "Ohring", gender: "der" },
  { word: "Option", gender: "die" },
  { word: "Ordner", gender: "der" },
  { word: "Ordnung", gender: "die" },
  { word: "Online-Banking", gender: "das" },
  { word: "Pannendienst", gender: "der" },
  { word: "Parfüm", gender: "das" },
  { word: "Partei", gender: "die" },
  { word: "Passwort", gender: "das" },
  { word: "Pausenregel", gender: "die" },
  { word: "Pflaster", gender: "das" },
  { word: "Pflegedienst", gender: "der" },
  { word: "Physik", gender: "die" },
  { word: "PIN", gender: "die" },
  { word: "Pinsel-Set", gender: "das" },
  { word: "Pinzette", gender: "die" },

  { word: "Privatschule", gender: "die" },
  { word: "Projekt", gender: "das" },
  { word: "Prospekt", gender: "der" },
  { word: "Prozent", gender: "das" },
  { word: "Prüfung", gender: "die" },
  { word: "Quittung", gender: "die" },
  { word: "Rad", gender: "das" },
  { word: "Radweg", gender: "der" },
  { word: "Rasierapparat", gender: "der" },
  { word: "Raum", gender: "der" },
  { word: "Realschule", gender: "die" },
  { word: "Rechnung", gender: "die" },
  { word: "Rechtsberatung", gender: "die" },
  { word: "Reinigungsunternehmen", gender: "das" },
  { word: "Reisebus", gender: "der" },
  { word: "Reisedokument", gender: "das" },
  { word: "Ruhe", gender: "die" },
  { word: "Rundfunkbeitrag", gender: "der" },
  { word: "Rundgang", gender: "der" },
  { word: "Salbe", gender: "die" },
  { word: "Sand", gender: "der" },
  { word: "Satz", gender: "der" },
  { word: "Säule", gender: "die" },
  { word: "Schachtel", gender: "die" },
  { word: "Schaden", gender: "der" },
  { word: "Schalter", gender: "der" },
  { word: "Schere", gender: "die" },
  { word: "Schichtarbeit", gender: "die" },
  { word: "Schlafsack", gender: "der" },
  { word: "Schleier", gender: "der" },
  { word: "Schmerzmittel", gender: "das" },
  { word: "Schmuck", gender: "der" },
  { word: "Schnitzel", gender: "das" },
  { word: "Schraube", gender: "die" },
  { word: "Schritt", gender: "der" },
  { word: "Serie", gender: "die" },
  { word: "Service", gender: "der" },
  { word: "Serviette", gender: "die" },
  { word: "Sinn", gender: "der" },
  { word: "Skigebiet", gender: "das" },
  { word: "Software", gender: "die" },
  { word: "Softwareprogramm", gender: "das" },
  { word: "Solidarität", gender: "die" },
  { word: "Sorge", gender: "die" },
  { word: "Speisekarte", gender: "die" },
  { word: "Stau", gender: "der" },
  { word: "Staubsauger", gender: "der" },
  { word: "Stellenangebot", gender: "das" },
  { word: "Stimmung", gender: "die" },
  { word: "Störung", gender: "die" },
  { word: "Strafe", gender: "die" },
  { word: "Stromkabel", gender: "das" },
  { word: "Studienplatz", gender: "der" },
  { word: "Studium", gender: "das" },
  { word: "Stundenlohn", gender: "der" },
  { word: "Stundenplan", gender: "der" },
  { word: "Sturm", gender: "der" },
  { word: "Sympathie", gender: "die" },
  { word: "Tabelle", gender: "die" },
  { word: "Tabellenkalkulation", gender: "die" },
  { word: "Talkshow", gender: "die" },
  { word: "Tanzfläche", gender: "die" },
  { word: "Tanzkurs", gender: "der" },
  { word: "Tarif", gender: "der" },

  { word: "Ticket", gender: "das" },
  { word: "Tief", gender: "die" },
  { word: "Tierhaltung", gender: "die" },
  { word: "Tofu", gender: "der" },
  { word: "Tonaufnahme", gender: "die" },
  { word: "Topangebot", gender: "das" },
  { word: "Tourismus", gender: "der" },
  { word: "Tradition", gender: "die" },
  { word: "Traum", gender: "der" },
  { word: "Trauung", gender: "die" },
  { word: "Trinkgeld", gender: "das" },
  { word: "Typ", gender: "der" },
  { word: "Urin", gender: "der" },
  { word: "Urin-Untersuchung", gender: "die" },
  { word: "Urlaubsfoto", gender: "das" },
  { word: "Urlaubsreise", gender: "die" },
  { word: "Ursache", gender: "die" },
  { word: "Veranstaltung", gender: "die" },
  { word: "Verband", gender: "der" },
  { word: "Verein", gender: "der" },
  { word: "Verkehrsmeldung", gender: "die" },
  { word: "Verkehrsverbindung", gender: "der" },
  { word: "Überraschung", gender: "die" },
  { word: "Überstunde", gender: "die" },
  { word: "Übung", gender: "die" },
  { word: "Uhrzeit", gender: "die" },
  { word: "Umgebung", gender: "die" },
  { word: "Universität", gender: "die" },
  { word: "Unterkunft", gender: "die" },
  { word: "Unterricht", gender: "der" },
  { word: "Versicherung", gender: "die" },
  { word: "Versicherungsschutz", gender: "der" },
  { word: "Vitamin", gender: "das" },
  { word: "Vollzeit", gender: "die" },
  { word: "Voraussetzung", gender: "die" },
  { word: "Vorort", gender: "der" },
  { word: "Wohlbefinden", gender: "das" },
  { word: "Wohnungseinrichtung", gender: "die" },
  { word: "Wagen", gender: "der" },
  { word: "Wärme", gender: "die" },
  { word: "Weiterbildung", gender: "die" },
  { word: "Welt", gender: "die" },
  { word: "Werk", gender: "das" },
  { word: "Wetterbericht", gender: "der" },
  { word: "Wochenende", gender: "das" },
  { word: "Wochentag", gender: "der" },
  { word: "Zahlung", gender: "die" },
  { word: "Zahn", gender: "der" },
  { word: "Zahnbürste", gender: "die" },
  { word: "Zeitschrift", gender: "die" },
  { word: "Zelt", gender: "das" },
  { word: "Zentrum", gender: "das" },
  { word: "Zettel", gender: "der" },
  { word: "Zeugnis", gender: "das" },
  { word: "Zielgruppe", gender: "die" },
  { word: "Zwilling", gender: "der" },
];
const grammatik = [
  {
    text: "Das ist ___ Auto.",
    options: ["ein", "eine", "einen"],
    correct: "ein",
    explanation:
      "Das Wort 'Auto' ist neutral, daher benutzt man 'ein' im Nominativ.",
  },
  {
    text: "Der Hund gehört ___ Mann.",
    options: ["dem", "den", "der"],
    correct: "dem",
    explanation: "Das Verb 'gehören' verlangt den Dativ, daher 'dem Mann'.",
  },
  {
    text: "Ich sehe ___ Katze.",
    options: ["die", "der", "den"],
    correct: "die",
    explanation: "Das Verb 'sehen' verlangt den Akkusativ, daher 'die Katze'.",
  },
  {
    text: "Wir sprechen über ___ Film.",
    options: ["den", "dem", "der"],
    correct: "den",
    explanation:
      "Die Präposition 'über' verlangt den Akkusativ, daher 'den Film'.",
  },
  {
    text: "Ich gebe ___ Kind ein Geschenk.",
    options: ["dem", "den", "der"],
    correct: "dem",
    explanation:
      "Das Verb 'geben' verlangt den Dativ für das Objekt, daher 'dem Kind'.",
  },
  {
    text: "Das Buch liegt auf ___ Tisch.",
    options: ["dem", "den", "der"],
    correct: "dem",
    explanation:
      "Das Verb 'liegen' verlangt den Dativ, da es eine Position beschreibt.",
  },
  {
    text: "Ich gehe in ___ Schule.",
    options: ["die", "der", "das"],
    correct: "die",
    explanation:
      "Das Verb 'gehen in' verlangt den Akkusativ, daher 'die Schule'.",
  },
  {
    text: "Das ist das Fahrrad ___ Jungen.",
    options: ["des", "der", "dem"],
    correct: "des",
    explanation: "Das Genitivobjekt 'des Jungen' zeigt Besitz an.",
  },
  {
    text: "Die Lampe hängt über ___ Tisch.",
    options: ["dem", "den", "der"],
    correct: "dem",
    explanation:
      "Das Verb 'hängen' im statischen Zustand verlangt den Dativ, daher 'dem Tisch'.",
  },
  {
    text: "Ich stelle die Vase auf ___ Tisch.",
    options: ["den", "dem", "der"],
    correct: "den",
    explanation:
      "Das Verb 'stellen' (Bewegung) verlangt den Akkusativ, daher 'den Tisch'.",
  },
  {
    text: "Er wartet auf ___ Bus.",
    options: ["den", "dem", "der"],
    correct: "den",
    explanation:
      "Die Präposition 'auf' mit dem Verb 'warten' verlangt den Akkusativ.",
  },
  {
    text: "Die Schlüssel sind in ___ Tasche.",
    options: ["der", "die", "den"],
    correct: "der",
    explanation:
      "Die Präposition 'in' zeigt hier eine Position an, daher Dativ 'der Tasche'.",
  },
  {
    text: "Hast du ___ Bleistift gesehen?",
    options: ["den", "dem", "der"],
    correct: "den",
    explanation:
      "Das Verb 'sehen' verlangt den Akkusativ, daher 'den Bleistift'.",
  },
  {
    text: "Ich freue mich auf ___ Wochenende.",
    options: ["das", "dem", "den"],
    correct: "das",
    explanation:
      "Die Präposition 'auf' in diesem Zusammenhang verlangt den Akkusativ.",
  },
  {
    text: "Das ist der Freund ___ Schwester.",
    options: ["der", "den", "des"],
    correct: "der",
    explanation: "'Der Schwester' ist im Genitiv, da es den Besitz ausdrückt.",
  },
];
const wortschatz = [
  {
    text: "Der Himmel ist ___.",
    options: ["blau", "rot", "grün"],
    correct: "blau",
    explanation:
      "Der Himmel ist normalerweise blau, außer bei Sonnenauf- oder -untergang.",
  },
  {
    text: "Ein Apfel ist ___.",
    options: ["rot", "blau", "weiß"],
    correct: "rot",
    explanation: "Äpfel sind oft rot, obwohl es auch grüne und gelbe gibt.",
  },
  {
    text: "Das Gegenteil von 'alt' ist ___.",
    options: ["jung", "klein", "groß"],
    correct: "jung",
    explanation: "Das Gegenteil von 'alt' (alt) ist 'jung' (jung).",
  },
  {
    text: "Die Sonne scheint am ___.",
    options: ["Tag", "Nacht", "Abend"],
    correct: "Tag",
    explanation: "Die Sonne scheint nur tagsüber.",
  },
  {
    text: "Ein Tisch ist ___.",
    options: ["groß", "lang", "kurz"],
    correct: "groß",
    explanation: "Tische sind normalerweise groß genug, um daran zu sitzen.",
  },
  {
    text: "Das Gegenteil von 'hell' ist ___.",
    options: ["dunkel", "leicht", "klar"],
    correct: "dunkel",
    explanation: "'Dunkel' ist das Gegenteil von 'hell'.",
  },
  {
    text: "Das Wasser ist ___.",
    options: ["kalt", "trocken", "hart"],
    correct: "kalt",
    explanation: "Wasser ist oft kalt, vor allem in der Natur.",
  },
  {
    text: "Der Baum ist ___.",
    options: ["grün", "blau", "rot"],
    correct: "grün",
    explanation: "Bäume haben grüne Blätter, außer im Herbst.",
  },
  {
    text: "Das Gegenteil von 'schnell' ist ___.",
    options: ["langsam", "kurz", "leise"],
    correct: "langsam",
    explanation: "Langsam bedeutet das Gegenteil von schnell.",
  },
  {
    text: "Milch ist ___.",
    options: ["weiß", "rot", "gelb"],
    correct: "weiß",
    explanation: "Milch ist normalerweise weiß.",
  },
  {
    text: "Das Gegenteil von 'groß' ist ___.",
    options: ["klein", "kurz", "eng"],
    correct: "klein",
    explanation: "'Klein' bedeutet das Gegenteil von 'groß'.",
  },
  {
    text: "Der Hund ist ___.",
    options: ["schnell", "langsam", "klar"],
    correct: "schnell",
    explanation: "Hunde können oft schnell laufen.",
  },
  {
    text: "Der Stuhl ist ___.",
    options: ["hart", "weich", "lang"],
    correct: "hart",
    explanation: "Stühle sind oft hart, damit sie stabil sind.",
  },
  {
    text: "Der Schnee ist ___.",
    options: ["weiß", "gelb", "grün"],
    correct: "weiß",
    explanation: "Schnee ist immer weiß, wenn er frisch ist.",
  },
  {
    text: "Der Sommer ist ___.",
    options: ["warm", "kalt", "klar"],
    correct: "warm",
    explanation: "Der Sommer ist normalerweise warm.",
  },
];

export { words, grammatik, wortschatz };
